/**
 * @authms/api-mfa — Auto-generated from mfa-service swagger.json
 * Generated: 2026-06-27
 * DO NOT EDIT — regenerated by scripts/generate_sdk_api_packages.py
 */

import type { ApiClient } from '@authms/core';

// ====== API Functions (tree-shakeable: independent exports) ======

/** Setup TOTP MFA method (returns provisioning URI and QR code) */
export function setupTotp(client: ApiClient): Promise<unknown> {
  return client.post('/mfa/api/v1/mfa/totp/setup');
}

/** Verify TOTP setup with a test code */
export function verifyTotp(client: ApiClient, data: { code: string }): Promise<void> {
  return client.post('/mfa/api/v1/mfa/totp/verify', data);
}

/** Enable TOTP after successful verification */
export function enableTotp(client: ApiClient, data: { code: string }): Promise<void> {
  return client.post('/mfa/api/v1/mfa/totp/enable', data);
}

/** Disable TOTP MFA method */
export function disableTotp(client: ApiClient): Promise<void> {
  return client.post('/mfa/api/v1/mfa/totp/disable');
}

/** Get available MFA methods for the current user */
export function getMfaMethods(client: ApiClient): Promise<unknown[]> {
  return client.get('/mfa/api/v1/mfa/methods');
}

/** Send SMS verification code to a phone number */
export function sendSmsCode(client: ApiClient, data: { phone: string }): Promise<void> {
  return client.post('/mfa/api/v1/mfa/sms/send', data);
}

/** Verify SMS code */
export function verifySmsCode(client: ApiClient, data: { code: string }): Promise<void> {
  return client.post('/mfa/api/v1/mfa/sms/verify', data);
}

/** Generate new backup codes */
export function generateBackupCodes(client: ApiClient): Promise<string[]> {
  return client.post('/mfa/api/v1/mfa/backup-codes/generate');
}

/** Get existing backup codes (masked) */
export function getBackupCodes(client: ApiClient): Promise<string[]> {
  return client.get('/mfa/api/v1/mfa/backup-codes');
}

/** Get push challenge for MFA verification */
export function getPushChallenge(client: ApiClient): Promise<unknown> {
  return client.get('/mfa/api/v1/mfa/push/challenge');
}
