/**
 * @authms/api-tenant — Auto-generated from tenant-service swagger.json
 * Generated: 2026-06-27
 * DO NOT EDIT — regenerated by scripts/generate_sdk_api_packages.py
 */

import type { ApiClient } from '@authms/core';

// ====== Types ======

export interface Tenant {
  id: string;
  name: string;
  displayName?: string;
  status?: string;
  membershipApproval?: string;
  plan?: string;
  maxUsers?: number;
  createdAt?: string;
  [key: string]: unknown;
}

export interface TenantMember {
  id: string;
  userId: string;
  role: string;
  status: string;
}

export interface CreateTenantRequest {
  name: string;
  displayName?: string;
  plan?: string;
}

export interface AddMemberRequest {
  email: string;
  role: string;
}

// ====== API Functions (tree-shakeable: independent exports) ======

/** Create a new tenant */
export function createTenant(client: ApiClient, data: CreateTenantRequest): Promise<Tenant> {
  return client.post('/tenant/api/v1/admin/tenants', data);
}

/** Get tenant by ID */
export function getTenant(client: ApiClient, tenantId: string): Promise<Tenant> {
  return client.get('/tenant/api/v1/tenants/' + tenantId);
}

/** Update tenant settings */
export function updateTenant(client: ApiClient, tenantId: string, data: Record<string, unknown>): Promise<Tenant> {
  return client.put('/tenant/api/v1/tenants/' + tenantId, data);
}

/** List members of a tenant */
export function listMembers(client: ApiClient, tenantId: string): Promise<TenantMember[]> {
  return client.get('/tenant/api/v1/tenants/' + tenantId + '/members');
}

/** Add a member to a tenant */
export function addMember(client: ApiClient, tenantId: string, data: AddMemberRequest): Promise<TenantMember> {
  return client.post('/tenant/api/v1/tenants/' + tenantId + '/members', data);
}

/** Remove a member from a tenant */
export function removeMember(client: ApiClient, tenantId: string, userId: string): Promise<void> {
  return client.delete('/tenant/api/v1/tenants/' + tenantId + '/members/' + userId);
}

/** Invite a user to join a tenant */
export function inviteMember(client: ApiClient, tenantId: string, data: AddMemberRequest): Promise<void> {
  return client.post('/tenant/api/v1/tenants/' + tenantId + '/invitations', data);
}

/** Get pending invitations for a tenant */
export function getInvitations(client: ApiClient, tenantId: string): Promise<unknown[]> {
  return client.get('/tenant/api/v1/tenants/' + tenantId + '/invitations');
}

/** Accept a tenant invitation by token */
export function acceptInvitation(client: ApiClient, token: string): Promise<void> {
  return client.post('/tenant/api/v1/tenants/invitations/' + token + '/accept');
}

/** Get membership applications for a tenant */
export function getApplications(client: ApiClient, tenantId: string): Promise<unknown[]> {
  return client.get('/tenant/api/v1/tenants/' + tenantId + '/applications');
}
