/**
 * @authms/api-billing — Auto-generated from billing-service swagger.json
 * Generated: 2026-06-27
 * DO NOT EDIT — regenerated by scripts/generate_sdk_api_packages.py
 */

import type { ApiClient } from '@authms/core';

// ====== API Functions (tree-shakeable: independent exports) ======

/** Get available billing plans (public endpoint) */
export function getPlans(client: ApiClient): Promise<unknown[]> {
  return client.get('/billing/api/v1/public/plans');
}

/** Get current tenant subscription */
export function getSubscription(client: ApiClient): Promise<unknown> {
  return client.get('/billing/api/v1/billing/subscription');
}

/** Subscribe to a billing plan */
export function subscribe(client: ApiClient, data: { planId: string }): Promise<unknown> {
  return client.post('/billing/api/v1/billing/subscribe', data);
}

/** Cancel current subscription */
export function cancelSubscription(client: ApiClient): Promise<void> {
  return client.post('/billing/api/v1/billing/subscription/cancel');
}

/** Get current usage metrics */
export function getUsage(client: ApiClient): Promise<unknown> {
  return client.get('/billing/api/v1/billing/usage');
}

/** Get invoices list */
export function getInvoices(client: ApiClient): Promise<unknown[]> {
  return client.get('/billing/api/v1/billing/invoices');
}

/** Get a specific invoice by ID */
export function getInvoice(client: ApiClient, id: string): Promise<unknown> {
  return client.get('/billing/api/v1/billing/invoice/' + id);
}

/** Get account balance */
export function getBalance(client: ApiClient): Promise<unknown> {
  return client.get('/billing/api/v1/billing/balance');
}

/** Get feature gates for current tenant */
export function getFeatureGates(client: ApiClient): Promise<unknown> {
  return client.get('/billing/api/v1/billing/feature-gates');
}
