/**
 * @authms/api-identity — Auto-generated from identity-service swagger.json
 * Generated: 2026-06-27
 * DO NOT EDIT — regenerated by scripts/generate_sdk_api_packages.py
 */

import type { ApiClient } from '@authms/core';

// ====== Types ======

export interface LoginRequest {
  email?: string;
  phone?: string;
  username?: string;
  password: string;
  tenantId?: string;
}

export interface LoginResponse {
  accessToken: string;
  refreshToken: string;
  expiresIn: number;
  tokenType: string;
  userId: string;
  user: User;
}

export interface RegisterRequest {
  email?: string;
  phone?: string;
  username?: string;
  password: string;
  tenantId?: string;
  name?: string;
}

export interface RegisterResponse {
  accessToken: string;
  refreshToken: string;
  expiresIn: number;
  user: User;
}

export interface RefreshRequest {
  refreshToken: string;
}

export interface RefreshResponse {
  accessToken: string;
  refreshToken: string;
  expiresIn: number;
}

export interface User {
  id: string;
  username?: string;
  email?: string;
  phone?: string;
  displayName?: string;
  avatar?: string;
  status?: string;
  createdAt?: string;
  updatedAt?: string;
  [key: string]: unknown;
}

export interface UpdateProfileRequest {
  username?: string;
  displayName?: string;
  avatar?: string;
}

export interface ChangePasswordRequest {
  currentPassword: string;
  newPassword: string;
}

export interface VerifyEmailRequest {
  code: string;
}

export interface SendVerificationEmailRequest {
  email: string;
}

export interface ResetPasswordRequest {
  token: string;
  newPassword: string;
}

export interface ForgotPasswordRequest {
  email: string;
}

export interface CheckPermissionRequest {
  resource: string;
  action: string;
}

export interface CheckPermissionResponse {
  allowed: boolean;
}

export interface SwitchTenantRequest {
  tenantId: string;
}

export interface TenantInfo {
  id: string;
  name: string;
  displayName?: string;
  role?: string;
}

export interface RoleActivationRequest {
  role: string;
  duration?: number;
  justification?: string;
}

export interface RoleActivation {
  id: string;
  role: string;
  status: string;
  activatedAt: string;
  expiresAt?: string;
  revokedAt?: string;
}

// ====== API Functions (tree-shakeable: independent exports) ======

/** Authenticate with email/phone/username and password */
export function login(client: ApiClient, data: LoginRequest): Promise<LoginResponse> {
  return client.post('/identity/api/v1/auth/login', data);
}

/** Register a new user account */
export function register(client: ApiClient, data: RegisterRequest): Promise<RegisterResponse> {
  return client.post('/identity/api/v1/auth/register', data);
}

/** Refresh access token using refresh token */
export function refreshToken(client: ApiClient, data: RefreshRequest): Promise<RefreshResponse> {
  return client.post('/identity/api/v1/auth/refresh', data);
}

/** Get current user profile */
export function getProfile(client: ApiClient): Promise<User> {
  return client.get('/identity/api/v1/auth/me');
}

/** Update current user profile */
export function updateProfile(client: ApiClient, data: UpdateProfileRequest): Promise<User> {
  return client.put('/identity/api/v1/auth/me', data);
}

/** Logout current user (revokes tokens) */
export function logout(client: ApiClient): Promise<void> {
  return client.post('/identity/api/v1/auth/logout');
}

/** Verify email with verification code */
export function verifyEmail(client: ApiClient, data: VerifyEmailRequest): Promise<void> {
  return client.post('/identity/api/v1/auth/verify-email', data);
}

/** Send email verification code */
export function sendVerificationEmail(client: ApiClient, data: SendVerificationEmailRequest): Promise<void> {
  return client.post('/identity/api/v1/auth/send-verification-email', data);
}

/** Change password (requires current password) */
export function changePassword(client: ApiClient, data: ChangePasswordRequest): Promise<void> {
  return client.put('/identity/api/v1/auth/me/password', data);
}

/** Request password reset email */
export function forgotPassword(client: ApiClient, data: ForgotPasswordRequest): Promise<void> {
  return client.post('/identity/api/v1/auth/forgot-password', data);
}

/** Reset password with token from email */
export function resetPassword(client: ApiClient, data: ResetPasswordRequest): Promise<void> {
  return client.post('/identity/api/v1/auth/reset-password', data);
}

/** Check if current user has a specific permission */
export function checkPermission(client: ApiClient, data: CheckPermissionRequest): Promise<CheckPermissionResponse> {
  return client.post('/identity/api/v1/auth/check-permission', data);
}

/** Get current user's permissions list */
export function getPermissions(client: ApiClient): Promise<string[]> {
  return client.get('/identity/api/v1/auth/me/permissions');
}

/** Get current user's tenants */
export function getTenants(client: ApiClient): Promise<TenantInfo[]> {
  return client.get('/identity/api/v1/auth/me/tenants');
}

/** Switch active tenant */
export function switchTenant(client: ApiClient, data: SwitchTenantRequest): Promise<User> {
  return client.post('/identity/api/v1/auth/me/switch-tenant', data);
}

/** Request a role activation (PIM/JIT) */
export function requestRoleActivation(client: ApiClient, data: RoleActivationRequest): Promise<RoleActivation> {
  return client.post('/identity/api/v1/auth/me/role-activations', data);
}

/** Get active role activations */
export function getRoleActivations(client: ApiClient): Promise<RoleActivation[]> {
  return client.get('/identity/api/v1/auth/me/role-activations');
}

/** Delete current user account */
export function deleteAccount(client: ApiClient): Promise<void> {
  return client.delete('/identity/api/v1/auth/me');
}

/** Get current user's sessions */
export function getSessions(client: ApiClient): Promise<unknown[]> {
  return client.get('/identity/api/v1/auth/me/sessions');
}

/** Delete a specific session */
export function deleteSession(client: ApiClient, sessionId: string): Promise<void> {
  return client.delete('/identity/api/v1/auth/me/sessions/' + sessionId);
}

/** Get current user's MFA methods */
export function getMFAMethods(client: ApiClient): Promise<unknown[]> {
  return client.get('/identity/api/v1/auth/me/mfa-methods');
}

// ====== Module Augmentation ======
// 安装此包后，useAuthms().api.identity 自动获得类型

export interface IdentityApi {
  login: typeof login;
  register: typeof register;
  refreshToken: typeof refreshToken;
  getProfile: typeof getProfile;
  updateProfile: typeof updateProfile;
  logout: typeof logout;
  verifyEmail: typeof verifyEmail;
  sendVerificationEmail: typeof sendVerificationEmail;
  changePassword: typeof changePassword;
  forgotPassword: typeof forgotPassword;
  resetPassword: typeof resetPassword;
  checkPermission: typeof checkPermission;
  getPermissions: typeof getPermissions;
  getTenants: typeof getTenants;
  switchTenant: typeof switchTenant;
  requestRoleActivation: typeof requestRoleActivation;
  getRoleActivations: typeof getRoleActivations;
  deleteAccount: typeof deleteAccount;
  getSessions: typeof getSessions;
  deleteSession: typeof deleteSession;
  getMFAMethods: typeof getMFAMethods;
}

declare module '@authms/core' {
  interface RegisteredApis {
    identity: IdentityApi;
  }
}
